app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

adcampaign:
    resource: "@AppBundle/Resources/config/routing/adcampaign.yml"
    
    
    

